act_code: '23639'
requisite: Совместное решение Западно-Казахстанского областного маслихата от 9 марта 2005 года № 15-2 и акимата Западно-Казахстанской области от 21 февраля 2005 года № 53. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 14 апреля 2005 года № 2920. Утратило силу решением Западно-Казахстанского областного маслихата от 22 октября 2005 года № 22-5
title:
  rus: Об очередном призыве граждан призывного возраста на срочную военную службу весной и осенью 2005 года
  kaz: 2005 жылдың көктемінде және күзінде шақыру жасындағы азаматтарды мерзімді әскери қызметке кезекті шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-03-09
approved_by:
- '159000000001'
- '159000000002'
version_date:
  kaz: 2005-03-09
  rus: 2005-03-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/23639/kaz/09.03.2005
  rus: https://zan.gov.kz/client/#!/doc/23639/rus/09.03.2005
