act_code: '20740'
requisite: Атырау облыстық мәслихатының 2004 жылғы 26 мамырдағы № 131-III шешiмi және Атырау облыстық әкімиятының 27 сәуірдегі № 98-а қаулысы. Атырау облысының Әділет департаментінде 2004 жылғы 7 шілдеде № 2046 болып тіркелді
title:
  rus: Атырау облысындағы 2004-2006 жылдарға арналған аймақтық "Мәдени мұра" бағдарламасы туралы
  kaz: Атырау облысындағы 2004-2006 жылдарға арналған аймақтық "Мәдени мұра" бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-05-25
approved_by:
- '156000000001'
- '156000000002'
version_date:
  kaz: 2006-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/20740/kaz/18.10.2006
