act_code: '55856'
requisite: Шығыс Қазақстан облысы Зайсан ауданы әкімдігінің 2010 жылғы 2 қарашадағы № 122 қаулысы, Зайсан аудандық мәслихатының 2010 жылғы 3 қарашадағы № 25-3/4 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Зайсан аудандық әділет басқармасында 2010 жылғы 10 желтоқсанда № 5-11-125 тіркелді
title:
  rus: Зайсан қаласындағы 14-маусым атындағы көшенің атауын өзгерту туралы
  kaz: Зайсан қаласындағы 14-маусым атындағы көшенің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-02
approved_by:
- '157012000001'
- '157012000002'
version_date:
  kaz: 2010-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/55856/kaz/02.11.2010
