act_code: '51783'
requisite: Атырау қалалық мәслихатының 2010 жылғы 9 сәуірдегі № 192 бірлескен шешімі және қалалық әкімиятының 2010 жылғы 1 сәуірдегі № 281 қаулысы. Атырау қалалық Әділет басқармасында 2010 жылғы 20 сәуірде № 4-1-114 тіркелді
title:
  rus: Жаңа көшелер мен өткелдерге атау беру туралы
  kaz: Жаңа көшелер мен өткелдерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-09
approved_by:
- '156002000001'
- '156002000002'
version_date:
  kaz: 2014-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/51783/kaz/04.12.2014
