act_code: '10583'
requisite: Совместное решение Мангистауского областного маслихата и акима Мангистауской области от 20 июня 2001 года № 12/105. Зарегистрировано управлением юстиции Мангистауской области 28 июня 2001 года за № 471
title:
  rus: Об упразднении Ботагозского сельского округа Каракиянского района
  kaz: Қарақия ауданының Ботагөз селолық округiн тарату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-06-19
approved_by:
- '163000000002'
- '163000000003'
version_date:
  kaz: 2001-06-19
  rus: 2001-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/10583/kaz/19.06.2001
  rus: https://zan.gov.kz/client/#!/doc/10583/rus/19.06.2001
