act_code: '23587'
requisite: Совместное решение акима города Астаны от 15 марта 2005 года N 36 и маслихата города Астаны от 29 марта 2005 года N 131/17-III. Зарегистрировано Департаментом юстиции города Астаны 14 апреля 2005 года N 385. Утратило силу - совместным решением акима города Астаны от 21 декабря 2005 года N 50 и маслихата города Астаны от 23 декабря 2005 года N 219/28-III.
title:
  rus: О проведении призыва граждан в возрасте от 18 до 27 лет в ряды Вооруженных Сил, других войск и воинских формирований Республики Казахстан в апреле-июне и октябре-декабре 2005 года
  kaz: 2005 жылдың сәуір-маусым және қазан-желтоқсан айларында Қазақстан Республикасы Қарулы Күштерінің, басқа да әскерлері мен әскери құрамаларының қатарына 18 ден 27 жасқа дейінгі азаматтарды шақыруды жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-03-15
approved_by:
- '151000000001'
- '151000000002'
version_date:
  kaz: 2005-03-15
  rus: 2005-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/23587/kaz/15.03.2005
  rus: https://zan.gov.kz/client/#!/doc/23587/rus/15.03.2005
