act_code: '23587'
requisite: Совместное решение акима города Астаны от 15 марта 2005 года N 36 и маслихата города Астаны от 29 марта 2005 года N 131/17-III. Зарегистрировано Департаментом юстиции города Астаны 14 апреля 2005 года N 385. Утратило силу - совместным решением акима города Астаны от 21 декабря 2005 года N 50 и маслихата города Астаны от 23 декабря 2005 года N 219/28-III.
title:
  rus: О проведении призыва граждан в возрасте от 18 до 27 лет в ряды Вооруженных Сил, других войск и воинских формирований Республики Казахстан в апреле-июне и октябре-декабре 2005 года
  kaz: 2005 жылдың сәуір-маусым және қазан-желтоқсан айларында Қазақстан Республикасы Қарулы Күштерінің, басқа да әскерлері мен әскери құрамаларының қатарына 18 ден 27 жасқа дейінгі азаматтарды шақыруды жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-03-15
approved_by:
- '151000000001'
- '151000000002'
version_date:
  kaz: 2005-06-28
  rus: 2005-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/23587/kaz/28.06.2005
  rus: https://zan.gov.kz/client/#!/doc/23587/rus/28.06.2005
caused_by:
  code: '24721'
  requisite: "Cовместное решение Акима города Астаны от 28 июня 2005 года N 43 и Маслихата города Астаны от 30 июня 2005 года N 164/20-III.\r\nЗарегистрировано в Департаменте юстиции города Астаны 14 июля 2005 года N 399. Утратило силу совместным решением Акима города Астаны  и маслихата города Астаны от 21.12.2005 г. № 50, от 23.12.2005 г. № 219/28-III"
  title:
    rus: О внесении изменений в совместное решение акима города Астаны и маслихата города Астаны от 15 марта 2005 года N 36 и от 29 марта 2005 года N 131/117-III "О проведении призыва граждан 1978-1987 годов рождения в ряды Вооруженных Сил, других войск и воинских формирований Республики Казахстан в апреле-июне и октябре-декабре 2005 года"
    kaz: Астана қаласы әкімінің және Астана қаласының мәслихатының 2005 жылғы 15 наурыздағы N 36 және 2005 жылғы 29 наурыздағы N 131/17-ІІІ "2005 жылдың сәуір-маусым және қазан-желтоқсан айларында Қазақстан Республикасы Қарулы Күштерінің, басқа да әскерлері мен әскери құрамаларының қатарына 1978-1987 жылдары туған азаматтарды шақыруды жүргізу туралы" бірлескен шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/24721/rus
