act_code: '53349'
requisite: Совместное решение XXVIII сессии Маслихата города Алматы IV созыва от 4 июня 2010 года N 327 и постановление Акимата города Алматы от 10 июня 2010 года N 2/403. Зарегистрировано в Департаменте юстиции города Алматы 24 июня 2010 года за N 851
title:
  rus: О присвоении наименований улицам Алатауского и Ауэзовского районов города Алматы
  kaz: Алматы қаласы Алатау және Әуезов аудандарындағы көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-04
approved_by:
- '155000000001'
- '155000000002'
version_date:
  kaz: 2010-06-04
  rus: 2010-06-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/53349/kaz/04.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53349/rus/04.06.2010
