act_code: '38592'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 12 февраля 2008 года № 6/10-IV, постановление акимата города Риддера от 15 февраля 2008 года № 646. Зарегистрировано Управлением юстиции города Риддера Департамента юстиции Восточно-Казахстанской области 19 марта 2008 года за № 5-4-85
title:
  rus: О переименовании улиц, площади и проспекта имени Ленина
  kaz: Көшелерді, Ленин атындағы даңғылды және Ленин атындағы алаңды қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-12
approved_by:
- '157005000001'
- '157005000002'
version_date:
  kaz: 2008-02-15
  rus: 2008-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/38592/kaz/15.02.2008
  rus: https://zan.gov.kz/client/#!/doc/38592/rus/15.02.2008
