act_code: '2750'
requisite: Совместное решение Акима Акмолинской области от 23 октября 1998 года № 26 и Административного совета Акмолинской СЭЗ от 26 октября 1998 года № 5 Зарегистрировано управлением юстиции 06 мая 1999 года за № 23. Утратило силу решением акима Акмолинской области от 22 апреля 2013 года № 11
title:
  rus: Об установлении временных границ пригородной зоны столицы Республики Казахстан - города Астаны
  kaz: Қазақстан Республикасының бас қаласы - Астана қаласының қала маңы аймағының уақытша шекарасын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-10-22
approved_by:
- '151000000003'
- '152000000003'
version_date:
  kaz: 1998-10-22
  rus: 1998-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/2750/kaz/22.10.1998
  rus: https://zan.gov.kz/client/#!/doc/2750/rus/22.10.1998
