act_code: '29527'
requisite: 'Решение от 28.07.2006 №16/289, Маслихат Мангистауской области и постановление от 24.07.2006 №239 Акима Мангистауской области '
title:
  rus: Об отнесении поселка Умирзак к категории "aул (село)"
  kaz: Өмірзақ кентін "ауыл" санатына жатқызу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-07-28
approved_by:
- '163000000001'
- '163000000002'
version_date:
  kaz: 2015-05-21
  rus: 2015-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/29527/kaz/21.05.2015
  rus: https://zan.gov.kz/client/#!/doc/29527/rus/21.05.2015
caused_by:
  code: '91292'
  requisite: Решение от 21.05.2015 №25/390, Маслихат Мангистауской области и постановление   от 21.05.2015 № 148, Акимат Мангистауской области
  title:
    rus: 'О внесении изменений в совместное решение Мангистауского областного маслихата и акима Мангистауской области,в некоторые постановления акимата Мангистауской области и решения Мангистауского областного маслихата '
    kaz: 'Маңғыстау облыстық мәслихаты мен Маңғыстау облысы әкімінің  бірлескен шешіміне,кейбір Маңғыстау облысы әкімдігінің қаулылары мен Маңғыстау облыстық мәслихатының шешімдеріне өзгерістер енгізу туралы '
  link: https://zan.gov.kz/client/#!/doc/91292/rus
