act_code: '6722'
requisite: Решение Акмолинского областного маслихата и акима Акмолинской области от 15 июня 2000 года № С-3-04 Зарегистрировано управлением юстиции Акмолинской области 24 июля 2000 года № 261
title:
  rus: Об изменении границ некоторых сельских округов и образовании отдельных административно-территориальных единиц
  kaz: Жекелеген ауылдық округтердің шекарасын өзгерту және дербес әкімшілік-аумақтық бірліктер құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-06-14
approved_by:
- '152000000001'
- '152000000002'
version_date:
  kaz: 2015-02-17
  rus: 2015-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/6722/kaz/17.02.2015
  rus: https://zan.gov.kz/client/#!/doc/6722/rus/17.02.2015
caused_by:
  code: '87231'
  requisite: Постановление акимата Акмолинской области от 17 февраля 2015 года № А-2/65 и решение Акмолинского областного маслихата от 17 февраля 2015 года № 5С-34-6. Зарегистрировано Департаментом юстиции Акмолинской области 5 марта 2015 года № 4673
  title:
    rus: О внесении изменений в некоторые совместные решения акима Акмолинской области и Акмолинского областного маслихата, постановления акимата Акмолинской области  и решения Акмолинского областного маслихата об изменениях в административно-территориальном устройстве Акмолинской области
    kaz: Ақмола облысының әкімшілік-аумақтық құрылысындағы өзгерістер туралы Ақмола облысы әкімінің және Ақмола облыстық мәслихатының кейбір бірлескен  шешімдеріне, Ақмола облысы әкімдігінің қаулылары мен Ақмола облыстық мәслихатының шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87231/rus
