act_code: '6722'
requisite: Решение Акмолинского областного маслихата и акима Акмолинской области от 15 июня 2000 года № С-3-04 Зарегистрировано управлением юстиции Акмолинской области 24 июля 2000 года № 261
title:
  rus: Об изменении границ некоторых сельских округов и образовании отдельных административно-территориальных единиц
  kaz: Жекелеген ауылдық округтердің шекарасын өзгерту және дербес әкімшілік-аумақтық бірліктер құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-06-14
approved_by:
- '152000000001'
- '152000000002'
version_date:
  kaz: 2000-06-14
  rus: 2000-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/6722/kaz/14.06.2000
  rus: https://zan.gov.kz/client/#!/doc/6722/rus/14.06.2000
