act_code: '7376'
requisite: Совместное решение Северо-Казахстанского областного маслихата и акима Северо-Казахстанской области от 23 августа 2000 года № 5/3-156. Зарегистрировано управлением юстиции Северо-Казахстанской области 19 сентября 2000 года за № 149
title:
  rus: О переименовании села Красное Булаевского района в аул Ногайбай
  kaz: Булаев ауданы Красное селосының атауын Ноғайбай ауылы деп өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-08-22
approved_by:
- '165000000001'
- '165000000002'
version_date:
  kaz: 2016-04-19
  rus: 2016-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/7376/kaz/19.04.2016
  rus: https://zan.gov.kz/client/#!/doc/7376/rus/19.04.2016
caused_by:
  code: '102541'
  requisite: Совместное постановление акимата Северо-Казахстанской области от 19 апреля 2016 года № 125 и решение маслихата Северо-Казахстанской области от 19 апреля 2016 года № 2/5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 мая 2016 года № 3757
  title:
    rus: О некоторых вопросах административно-территориального устройства Северо-Казахстанской области
    kaz: Солтүстік Қазақстан облысының әкімшілік-аумақтық құрылысының кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/102541/rus
