act_code: '29460'
requisite: 'Решение от 28.07.2006 №16/288, Маслихат Мангистауской области и постановление 31.05.2006 № 188 Акима Мангистауской области '
title:
  rus: Об образовании села Тажен в составе Акжигитского сельского округа Бейнеуского района
  kaz: Бейнеу ауданының Ақжігіт ауылдық округінің құрамында Тәжен аулын құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-05-31
approved_by:
- '163000000001'
- '163000000002'
version_date:
  rus: 2006-05-31
source:
  rus: https://zan.gov.kz/client/#!/doc/29460/rus/31.05.2006
