act_code: '20159'
requisite: Совместное решение маслихата Атырауской области от 28 апреля 2004 года № 93-III, и решение акима Атырауской области от 8 апреля 2004 года № 46. Зарегистрировано Департаментом юстиции Атырауской области 2 июня 2004 года № 1986
title:
  rus: О проведении очередного призыва граждан на срочную военную службу на территории области в апреле-июне и октябре-декабре 2004 года
  kaz: Облыс аумағындағы азаматтарды 2004 жылдың сәуір-маусымында және қазан-желтоқсанында кезекті мерзімді әскери қызметке шақыруды өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-04-27
approved_by:
- '156000000002'
- '156000000003'
version_date:
  kaz: 2004-04-27
  rus: 2004-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/20159/kaz/27.04.2004
  rus: https://zan.gov.kz/client/#!/doc/20159/rus/27.04.2004
