act_code: '38263'
requisite: Совместное постановление областного акимата от 4 февраля 2008 года № 35 и решение Атырауского областного маслихата от 8 февраля 2008 года № 70-IV. Зарегистрировано Департаментом юстиции Атырауской области 11 марта 2008 года за № 2522
title:
  rus: О переименовании села Чапаево Тушыкудукского сельского округа Исатайского района в село Тушыкудук
  kaz: Исатай ауданы Тұщықұдық селолық округінің Чапаев селосын Тұщықұдық селосы деп қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-04
approved_by:
- '156000000001'
- '156000000002'
version_date:
  kaz: 2008-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/38263/kaz/08.02.2008
