act_code: '72225'
requisite: Решение маслихата Алматинской области от 12 апреля 2013 года N 15-104 и постановление акимата Алматинской области от 12 апреля 2013 года N114. Зарегистрировано Департаментом юстиции Алматинской области 24 апреля 2013 года N 2346
title:
  rus: Об упразднении Кокжидинского сельского округа Сарканского района и включении его территории в состав Лепсинского поселкового округа Сарканского района
  kaz: Сарқан ауданы Көкжиде ауылдық округін тарату және оның аумағын Сарқан ауданы Лепсі поселкелік округ құрамына енгiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-04-12
approved_by:
- '154000000001'
- '154000000002'
version_date:
  kaz: 2013-04-12
  rus: 2013-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/72225/kaz/12.04.2013
  rus: https://zan.gov.kz/client/#!/doc/72225/rus/12.04.2013
