act_code: '74370'
requisite: Решение акима аульного округа Жанаталап Жалагашского района Кызылординской области от 22 августа 2013 года N 4. Зарегистрировано Департаментом юстиции Кызылординской области 13 сентября 2013 года N 4515. Утратило силу решением акима аульного округа Жанаталап Жалагашского района Кызылординской области от 16 октября 2014 года N 6
title:
  rus: Об установлении ветеринарного режима карантинной зоны с введением ограничительных мероприятий
  kaz: Шектеу іс-шараларын енгізе отырып карантин аймағының ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-22
approved_by:
- '161006008001'
- '161006008001'
version_date:
  kaz: 2013-08-22
  rus: 2013-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/74370/kaz/22.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74370/rus/22.08.2013
