act_code: '64895'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 9 апреля 2012 года № 3/8-V, постановление акимата Шемонаихинского района Восточно-Казахстанской области от 9 апреля 2012 года № 470. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 23 апреля 2012 года за № 5-19-172
title:
  rus: О переименовании улицы города Шемонаиха Шемонаихинского района
  kaz: Шемонаиха ауданы Шемонаиха қаласы көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-09
approved_by:
- '157020000001'
- '157020000002'
version_date:
  kaz: 2012-04-09
  rus: 2012-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/64895/kaz/09.04.2012
  rus: https://zan.gov.kz/client/#!/doc/64895/rus/09.04.2012
