act_code: '6718'
requisite: Решение Акмолинского областного маслихата и акима Акмолинской области от 24 февраля 2000 года № С-08. Зарегистрировано Управлением юстиции Акмолинской области 24 июля 2000 года № 256
title:
  rus: О присвоении Трудовой средней школе Аккольского района имени Героя Советского Союза, Халық Қаһарманы С. Нурмагамбетова
  kaz: Ақкөл ауданындағы Трудовое орта мектебіне Кеңес Одағының Батыры, Халық Қаһарманы С. Нұрмағамбетовтің атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-02-24
approved_by:
- '152000000001'
- '152000000002'
version_date:
  kaz: 2000-02-24
  rus: 2000-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/6718/kaz/24.02.2000
  rus: https://zan.gov.kz/client/#!/doc/6718/rus/24.02.2000
