act_code: '62627'
requisite: Решение Кызылординского городского маслихата от 21 декабря 2011 года № 51/3 и Постановление Кызылординского городского акимата от 21 декабря 2011 года № 2524. Зарегистрировано Департаментом юстиции Кызылординской области 12 января 2012 года за № 10-1-203
title:
  rus: О наименовании улиц города Кызылорды
  kaz: Қызылорда қаласының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-21
approved_by:
- '161002000001'
- '161002000002'
version_date:
  kaz: 2012-09-27
  rus: 2012-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/62627/kaz/27.09.2012
  rus: https://zan.gov.kz/client/#!/doc/62627/rus/27.09.2012
caused_by:
  code: '68099'
  requisite: Решение Кызылординского городского маслихата от 27 сентября 2012 года N 9/2 и Постановление Кызылординского городского акимата от 27 сентября 2012 года N 4548. Зарегистрировано Департаментом юстиции Кызылординской области 17 октября 2012 года за N 4324. Утратило силу решением Кызылординского городского маслихата от 16 июля 2013 года N 19/5 и постановлением Кызылординского городского акимата от 16 июля 2013 года N 589
  title:
    rus: О внесении изменений в некоторые решения Кызылординского городского маслихата и постановления акимата города Кызылорда
    kaz: Кейбір Қызылорда қалалық мәслихатының шешімдері мен Қызылорда қаласы әкімдігінің қаулыларына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/68099/rus
