act_code: '62627'
requisite: Решение Кызылординского городского маслихата от 21 декабря 2011 года № 51/3 и Постановление Кызылординского городского акимата от 21 декабря 2011 года № 2524. Зарегистрировано Департаментом юстиции Кызылординской области 12 января 2012 года за № 10-1-203
title:
  rus: О наименовании улиц города Кызылорды
  kaz: Қызылорда қаласының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-21
approved_by:
- '161002000001'
- '161002000002'
version_date:
  kaz: 2011-12-21
  rus: 2011-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/62627/kaz/21.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62627/rus/21.12.2011
