act_code: '113096'
requisite: Решение от 27.09.2001 №43, Маслихат Аральского района, Аким Аральского района
title:
  rus: Аудандық ономастикалық комиссияның Арал қаласындағы көше атын өзгерту жөніндегі ұсыныстар туралы
  kaz: Аудандық ономастикалық комиссияның Арал қаласындағы көше атын өзгерту жөніндегі ұсыныстар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-09-26
approved_by:
- '161003000002'
- '161003000003'
version_date:
  kaz: 2001-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/113096/kaz/26.09.2001
