act_code: '9876'
requisite: Совместное решение областного маслихата и акимата Западно-Казахстанской области от 6 июля 2001 года № 13-5. Зарегистрировано Управлением юстиции Западно-Казахстанской области 3 сентября 2001 года № 1070. Утратило силу решением Западно-Казахстанского областного маслихата от 8 февраля 2005 года № 14-24
title:
  rus: О предельных (максимальных) размерах земельных участков, предоставляемых в собственность и долгосрочное землепользование
  kaz: Жер телімдерін меншікке және ұзақ мерзімді пайдалануға берудің шекті (барынша көп) мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-07-05
approved_by:
- '159000000001'
- '159000000002'
version_date:
  kaz: 2001-07-05
  rus: 2001-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/9876/kaz/05.07.2001
  rus: https://zan.gov.kz/client/#!/doc/9876/rus/05.07.2001
