act_code: '18691'
requisite: Атырау облыстық мәслихатының 2003 жылғы 12 желтоқсандағы № 26-III шешiмi және Атырау облысы әкімінің 2003 жылғы 30 қыркүйектегі № 200 қаулысы. Атырау облысының Әділет басқармасында 2004 жылғы 21 қаңтарда № 1787 болып тіркелді
title:
  rus: Тілдерді қолдану дамытудың 2003-2004  жылдарға арналған өңірлік  бағдарламасы туралы
  kaz: Тілдерді қолдану дамытудың 2003-2004  жылдарға арналған өңірлік  бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-12
approved_by:
- '156000000001'
- '156000000002'
version_date:
  kaz: 2003-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/18691/kaz/12.12.2003
