act_code: '59646'
requisite: Постановление Кызылординского городского акимата от 20 июня 2011 года № 1508 и решение Кызылординского городского маслихата от 20 июня 2011 года № 44/4. Зарегистрировано Департаментом юстиции Кызылординской области 11 июля 2011 года за № 10-1-178
title:
  rus: О наименовании улиц города Кызылорда
  kaz: Қызылорда қаласындағы көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-20
approved_by:
- '161002000001'
- '161002000002'
version_date:
  kaz: 2013-07-16
  rus: 2013-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/59646/kaz/16.07.2013
  rus: https://zan.gov.kz/client/#!/doc/59646/rus/16.07.2013
caused_by:
  code: '73941'
  requisite: Решение Кызылординского городского маслихата от 16 июля 2013 года N 19/5 и Постановление Кызылординского городского акимата от 16 июля 2013 года N 589. Зарегистрировано Департаментом юстиции Кызылординской области 13 августа 2013 года за N 4494
  title:
    rus: О внесении изменений в некоторые постановления акимата города Кызылорда и решения Кызылординского городского маслихата
    kaz: Кейбір Қызылорда қаласы әкімдігінің қаулылары мен Қызылорда қалалық мәслихатының шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/73941/rus
