act_code: '47115'
requisite: Решение ХIХ-й сессии маслихата города Алматы IV-го созыва от 25 июня 2009 года N 217 и постановление акимата города Алматы от 2 июля 2009 года N 4/426. Зарегистрировано в Департаменте юстиции города Алматы 31 июля 2009 года за N 820
title:
  rus: О присвоении наименований микрорайону и отдельным улицам Алатауского района
  kaz: Алатау ауданында жаңа құрылған ықшамауданға және жеке көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-25
approved_by:
- '155000000001'
- '155000000002'
version_date:
  kaz: 2009-06-25
  rus: 2009-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/47115/kaz/25.06.2009
  rus: https://zan.gov.kz/client/#!/doc/47115/rus/25.06.2009
