act_code: '53278'
requisite: Шығыс Қазақстан облысы Зайсан аудандық мәслихатының 2010 жылғы 26 мамырдағы № 21-3 шешімі, Шығыс Қазақстан облысы Зайсан ауданы әкімдігінің 2010 жылғы 26 мамырдағы № 1300 қаулысы. Шығыс Қазақстан облысы Әділет департаментінің Зайсан аудандық әділет басқармасында 2010 жылғы 28 маусымда № 5-11-117 тіркелді
title:
  rus: Зайсан қаласындағы Ю. Гагарин атындағы көшенің атауын өзгерту туралы
  kaz: Зайсан қаласындағы Ю. Гагарин атындағы көшенің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-26
approved_by:
- '157012000001'
- '157012000002'
version_date:
  kaz: 2010-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/53278/kaz/26.05.2010
