act_code: '5098'
requisite: Решение Актюбинского областного Маслихата и Акима Актюбинской области, принятое на второй сессии от 17 ноября 1999 года № 7. Зарегистрировано Управлением юстиции Актюбинской области 14 января 2000 года № 329
title:
  rus: О переименовании сельских округов и сел в Хромтауском районе
  kaz: Хромтау ауданының ауылдық округтері мен ауылдарының аттарын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-11-17
approved_by:
- '153000000001'
- '153000000002'
version_date:
  kaz: 2015-12-11
  rus: 2015-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/5098/kaz/11.12.2015
  rus: https://zan.gov.kz/client/#!/doc/5098/rus/11.12.2015
caused_by:
  code: '98669'
  requisite: Постановление акимата Актюбинской области от 11 декабря 2015 года № 452 и решение Актюбинского областного маслихата от 11 декабря 2015 года № 359. Зарегистрировано Департаментом юстиции Актюбинской области 22 января 2016 года № 4699
  title:
    rus: О внесении изменений в некоторые нормативные правовые акты по вопросам административно - территориального устройства Актюбинской области и признании утратившими силу некоторых постановлений акимата и решений маслихата Актюбинской области
    kaz: Ақтөбе облысының әкімшілік-аумақтық құрылысы мәселелері бойынша кейбір нормативтік құқықтық актілерге өзгерістер енгізу және Ақтөбе облысы әкімдігінің кейбір қаулыларының және мәслихатының шешімдерінің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/98669/rus
