act_code: '60160'
requisite: Решение Западно-Казахстанского областного маслихата от 20 августа 2011 года № 34-13 и постановление акимата Западно-Казахстанской области от 28 декабря 2010 года № 329. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 24 августа 2011 года за № 3068
title:
  rus: Об упразднении некоторых населенных пунктов Жанибекского района Западно-Казахстанской области
  kaz: Батыс Қазақстан облысының Жәнібек ауданының кейбір елді мекендерін тарату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-08-20
approved_by:
- '159000000001'
- '159000000002'
version_date:
  kaz: 2011-08-20
  rus: 2011-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/60160/kaz/20.08.2011
  rus: https://zan.gov.kz/client/#!/doc/60160/rus/20.08.2011
