act_code: '56394'
requisite: Совместное решение маслихата Актюбинской области от 13 декабря 2010 года № 340 и постановление акимата Актюбинской области от 13 декабря 2010 года № 388. Зарегистрировано Департаментом юстиции Актюбинской области 5 января 2011 года № 3351
title:
  rus: О переименовании Ильинского сельского округа Алгинского района Актюбинской области в Акайский сельский округ
  kaz: Ақтөбе облысы Алға ауданы Ильинка ауылдық округін Ақай ауылдық округі деп қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-13
approved_by:
- '153000000001'
- '153000000002'
version_date:
  kaz: 2010-12-13
  rus: 2010-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/56394/kaz/13.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56394/rus/13.12.2010
