act_code: '54894'
requisite: Алматы облысы Талғар аудандық мәслихатының 2010 жылғы 16 қыркүйектегі № 37-215 шешімі және Талғар ауданы әкімдігінің 2010 жылғы 16 қыркүйектегі № 09-713 қаулысы. Алматы облысы Талғар ауданының Әділет басқармасында 2010 жылғы 15 қазанда № 2-18-114 тіркелді
title:
  rus: Талғар ауданы Белбұлақ ауылдық округінің шекарасын (шегін) өзгерту туралы
  kaz: Талғар ауданы Белбұлақ ауылдық округінің шекарасын (шегін) өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-16
approved_by:
- '154013000001'
- '154013000002'
version_date:
  kaz: 2010-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/54894/kaz/16.09.2010
