act_code: '62018'
requisite: Совместное решение маслихата Кызылжарского района Северо-Казахстанской области от 18 ноября 2011 года № 41/4 и постановление акимата Кызылжарского района Северо-Казахстанской области от 18 ноября 2011 года № 518. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 21 декабря 2011 года № 13-8-157
title:
  rus: Об изменении границ села Карлуга Кызылжарского сельского округа Кызылжарского района
  kaz: Қызылжар ауданы Қызылжар ауылдық округі Карлуга ауылының шекараларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-18
approved_by:
- '165008000001'
- '165008000002'
version_date:
  kaz: 2018-11-26
  rus: 2018-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/62018/kaz/26.11.2018
  rus: https://zan.gov.kz/client/#!/doc/62018/rus/26.11.2018
caused_by:
  code: '126330'
  requisite: Совместное постановление акимата Кызылжарского района Северо-Казахстанской области от 26 ноября 2018 года № 451 и решение Кызылжарского районного маслихата Северо-Казахстанской области от 26 ноября 2018 года № 34/4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 ноября 2018 года № 5019
  title:
    rus: О внесении изменений в совместное постановление акимата Кызылжарского района Северо-Казахстанской области от 18 ноября 2011 года № 518 и решение Кызылжарского районного маслихата Северо-Казахстанской области от 18 ноября 2011 года № 41/1 «Об изменении границ села Карлуга Кызылжарского аульного округа Кызылжарского района»
    kaz: Солтүстік Қазақстан облысы Қызылжар аудандық әкімдігінің 2011 жылғы 18 қарашадағы № 518 және Солтүстік Қазақстан облысы Қызылжар аудандық мәслихатының 2011 жылғы 18 қарашадағы № 41/1 «Қызылжар ауданы Қызылжар ауылдық округі Карлуга селосының шекараларын өзгерту туралы» біріккен қаулысы мен шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126330/rus
