act_code: '62018'
requisite: Совместное решение маслихата Кызылжарского района Северо-Казахстанской области от 18 ноября 2011 года № 41/4 и постановление акимата Кызылжарского района Северо-Казахстанской области от 18 ноября 2011 года № 518. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 21 декабря 2011 года № 13-8-157
title:
  rus: Об изменении границ села Карлуга Кызылжарского сельского округа Кызылжарского района
  kaz: Қызылжар ауданы Қызылжар ауылдық округі Карлуга ауылының шекараларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-18
approved_by:
- '165008000001'
- '165008000002'
version_date:
  kaz: 2011-11-18
  rus: 2011-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/62018/kaz/18.11.2011
  rus: https://zan.gov.kz/client/#!/doc/62018/rus/18.11.2011
