act_code: '53077'
requisite: Алматы облысы Талғар аудандық мәслихатының 2010 жылғы 1 маусымдағы № 32-196 шешімі және Талғар ауданы әкімдігінің 2010 жылғы 1 маусымдағы № 06-381 қаулысы. Алматы облысы Талғар ауданының Әділет басқармасында 2010 жылғы 14 маусымда № 2-18-107 тіркелді
title:
  rus: Талғар ауданы елді мекендерінің шекарасын (шегін) өзгерту туралы
  kaz: Талғар ауданы елді мекендерінің шекарасын (шегін) өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-01
approved_by:
- '154013000001'
- '154013000002'
version_date:
  kaz: 2010-06-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/53077/kaz/01.06.2010
