act_code: '22669'
requisite: Совместное решение акимата Акмолинской области и Акмолинского областного Маслихата от 10 декабря 2004 года № ЗС-9-14. Зарегистрировано Департаментом юстиции Акмолинской области 18 января 2005 года № 2996
title:
  rus: Об упразднении некоторых сел Аршалынского и Жаксынского районов
  kaz: Аршалы және Жақсы аудандарының кейбір ауылдарын қысқарту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-10
approved_by:
- '152000000001'
- '152000000002'
version_date:
  kaz: 2004-12-10
  rus: 2004-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/22669/kaz/10.12.2004
  rus: https://zan.gov.kz/client/#!/doc/22669/rus/10.12.2004
