act_code: '45937'
requisite: Маңғыстау ауданы әкімдігі Тұщықұдық селосы әкімінің 2009 жылғы 30 сәуірдегі N 02 шешімі. Маңғыстау ауданының Әділет басқармасында 2009 жылғы 15 мамырда N 11-5-80 тіркелді. Күші жойылды – Маңғыстау облысы Маңғыстау ауданы әкімдігі Тұщықұдық селолық округі әкімінің 2016 жылғы 16 мамырдағы № 31 шешімімен
title:
  rus: Тұщықұдық селосы көшесіне А.Қ. Қодаровтың атағын беру туралы
  kaz: Тұщықұдық селосы көшесіне А.Қ. Қодаровтың атағын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-30
approved_by:
- '163004000001'
- '163004004001'
version_date:
  kaz: 2009-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/45937/kaz/30.04.2009
