act_code: '34665'
requisite: Постановление акимата Акмолинской области от 6 июля 2007 года № а-7/243 и решение Акмолинского областного маслихата от 6 июля 2007 года № 3С-28-6. Зарегистрировано Департаментом юстиции Акмолинской области 8 августа 2007 года № 3233
title:
  rus: Об установлении предельных (максимальных) размеров земельных участков, которые могут находиться в частной собственности в Акмолинской области
  kaz: Ақмола облысында жеке меншікте болуы мүмкін жер учаскелерінің шекті (ең жоғары) мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-06
approved_by:
- '152000000001'
- '152000000002'
version_date:
  kaz: 2019-09-06
  rus: 2019-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/34665/kaz/06.09.2019
  rus: https://zan.gov.kz/client/#!/doc/34665/rus/06.09.2019
caused_by:
  code: '134612'
  requisite: Постановление акимата Акмолинской области от 6 сентября 2019 года № А-9/424 и решение Акмолинского областного маслихата от 6 сентября 2019 года № 6С-37-3. Зарегистрировано Департаментом юстиции Акмолинской области 11 сентября 2019 года № 7377
  title:
    rus: О внесении изменения в постановление акимата Акмолинской области от 6 июля 2007 года № а-7/243 и решение Акмолинского областного маслихата от 6 июля 2007 года № 3С-28-6 «Об установлении предельных (максимальных) размеров земельных участков, которые могут находиться в частной собственности в Акмолинской области»
    kaz: «Ақмола облысында жеке меншікте болуы мүмкін жер учаскелерінің шекті (ең жоғары) мөлшерлерін белгілеу туралы» Ақмола облысы әкiмдiгiнiң 2007 жылғы 6 шілдедегі № а-7/243 қаулысына және Ақмола облыстық мәслихатының 2007 жылғы 6 шілдедегі № 3С-28-6 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134612/rus
