act_code: '54151'
requisite: Решение от 22.07.2010 №26/304, Акимат Мангистауской области, Маслихат Мангистауской области
title:
  rus: Об образовании сельского округа Саина Шапагатова Тупкараганского района
  kaz: Түпқараған ауданының Сайын Шапағатов селолық округын құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-22
approved_by:
- '163000000001'
- '163000000002'
version_date:
  rus: 2015-07-29
source:
  rus: https://zan.gov.kz/client/#!/doc/54151/rus/29.07.2015
