act_code: '54151'
requisite: Решение от 22.07.2010 №26/304, Акимат Мангистауской области, Маслихат Мангистауской области
title:
  rus: Об образовании сельского округа Саина Шапагатова Тупкараганского района
  kaz: Түпқараған ауданының Сайын Шапағатов селолық округын құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-22
approved_by:
- '163000000001'
- '163000000002'
version_date:
  kaz: 2015-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/54151/kaz/29.07.2015
caused_by:
  code: '93329'
  requisite: Решение от 29.07.2015 №27/413, Маслихат Мангистауской области, постановление от 29.07.2015 №224, Акимат Мангистауской области
  title:
    rus: О внесении изменений в постановление акимата Мангистауской области от 15 июля 2010 года № 266 и решение Мангистауского областного маслихата от 23 июля 2010 года № 26/304 «Об образовании сельского округа Саина Шапагатова Тупкараганского района»
    kaz: Маңғыстау облысы әкімдігінің 2010 жылғы 15 шілдедегі № 266 және Маңғыстау облыстық мәслихатының 2010 жылғы 23 шілдедегі № 26/304 «Түпқараған ауданының Сайын Шапағатов селолық округын құру туралы» қаулысы мен шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93329/rus
