act_code: '20651'
requisite: Совместное решение Акима города Астаны от 25 мая 2004 года N 26 и Маслихата города Астаны от 29 июня 2004 года N 56/9-III. Зарегистрировано Департаментом юстиции города Астаны 23 июля 2004 года N 338. Утратило силу - совместным решением акима от 21 сентября 2006 года N 54 и маслихата города Астаны от 21 сентября 2006 года N 284/35-III
title:
  rus: Об установлении предельных (максимальных) размеров земельных участков, которые могут находиться в частной собственности граждан Республики Казахстан
  kaz: Қазақстан Республикасы азаматарының жеке меншігінде болуы мүмкін жер учаскелерінің шекті (ең жоғары) мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-05-24
approved_by:
- '151000000001'
- '151000000002'
version_date:
  kaz: 2004-05-24
  rus: 2004-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/20651/kaz/24.05.2004
  rus: https://zan.gov.kz/client/#!/doc/20651/rus/24.05.2004
