act_code: '25157'
requisite: Совместное решение Актюбинского областного маслихата от 4 августа 2005 года № 180 и постановление Акимата Актюбинской области от 4 августа 2005 года № 295. Зарегистрировано Департаментом юстиции Актюбинской области от 25 августа 2005 года N 3157
title:
  rus: О переменовании станции "Аккудук" на железнодорожной линии "Хромтау-Алтынсарино" станцией "Коктау"
  kaz: '"Хромтау-Алтынсарин" темір жолы бойындағы "Аққұдық" станциясының атауын "Көктау" деп өзгерту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-08-04
approved_by:
- '153000000001'
- '153000000002'
version_date:
  kaz: 2005-08-04
  rus: 2005-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/25157/kaz/04.08.2005
  rus: https://zan.gov.kz/client/#!/doc/25157/rus/04.08.2005
