act_code: '54086'
requisite: Шығыс Қазақстан облысы Аягөз аудандық мәслихатының 28 шілдедегі № 01-02/27-15 шешімі, Шығыс Қазақстан облысы Аягөз ауданы әкімдігінің 2010 жылғы 28 шілдедегі № 06 қаулысы. Шығыс Қазақстан облысы Аягөз аудандық әділет басқармасында 2010 жылғы 19 тамызда № 5-6-112 тіркелді
title:
  rus: Аягөз қаласының кейбір көшелерінің атауын өзгерту туралы
  kaz: Аягөз қаласының кейбір көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-28
approved_by:
- '157007000001'
- '157007000002'
version_date:
  kaz: 2010-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/54086/kaz/28.07.2010
