act_code: '25540'
requisite: Решение Мангистауского областного Маслихата от 28 сентября 2005 года № 12/217 и постановление акимата Мангистауской области от 27 июля 2005 года № 240. Зарегистрировано Департаментом юстиции Мангистауской области 17 октября 2005 года № 1925
title:
  rus: О переименовании населенного пункта Тельман в населенный пункт Саина Шапагатова
  kaz: Тельман елді мекенін Сайын Шапағатов елді мекені деп атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-09-28
approved_by:
- '163000000001'
- '163000000002'
version_date:
  kaz: 2005-09-28
  rus: 2005-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/25540/kaz/28.09.2005
  rus: https://zan.gov.kz/client/#!/doc/25540/rus/28.09.2005
