act_code: '10516'
requisite: Совместное решение Северо-Казахстанского областного Маслихата и Акима Северо-Казахстанской области от 12 октября 2001 года № 13/11-72 Зарегистрировано управлением юстиции Северо-Казахстанской области 1 ноября 2001 года за № 473. Утратило силу - решением акима Северо-Казахстанской области от 26 сентября 2011 года № 27
title:
  rus: Об организации призыва граждан Республики Казахстан на срочную военную службу на территории области в октябре-декабре 2001 года
  kaz: Облыс аумағындағы азаматтарды 2001 жылдың қазан-желтоқсанында мерзімді әскери қызметке шақыруды өткізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-10-11
approved_by:
- '165000000001'
- '165000000002'
version_date:
  kaz: 2001-10-11
  rus: 2001-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/10516/kaz/11.10.2001
  rus: https://zan.gov.kz/client/#!/doc/10516/rus/11.10.2001
