act_code: '52431'
requisite: Решение от 31.03.2010 №717/218, Акимат Кызылординской области, Маслихат Кызылординской области
title:
  rus: Қармақшы ауданындағы Жаңажол ауылын Дүр Оңғар есімімен қайта атау туралы
  kaz: Қармақшы ауданындағы Жаңажол ауылын Дүр Оңғар есімімен қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-31
approved_by:
- '161000000001'
- '161000000002'
version_date:
  kaz: 2010-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/52431/kaz/31.03.2010
