act_code: '44414'
requisite: Бейнеу ауданы әкімдігінің 2009 жылғы 26 қаңтардағы № 12 қаулысы және Бейнеу аудандық мәслихатының 2009 жылғы 26 қаңтардағы № 14/95 шешімі. Бейнеу ауданының Әділет басқармасында 2009 жылғы 12 ақпанда № 11-3-71 тіркелді
title:
  rus: Бейнеу және Сарға селоларының шекараларын өзгерту туралы
  kaz: Бейнеу және Сарға селоларының шекараларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-26
approved_by:
- '163007000001'
- '163007000002'
version_date:
  kaz: 2009-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/44414/kaz/26.01.2009
