act_code: '75687'
requisite: Решение Казалинского районного маслихата Кызылординской области от 1 ноября 2013 года № 152 и Постановление Казалинского районного акимата Кызылординской области от 1 ноября 2013 года № 282. Зарегистрировано Департаментом юстиции Кызылординской области 5 декабря 2013 года за № 4547. Утратило силу постановлением акимата Казалинского района Кызылординской области от 27 июля 2017 года № 152 и решением Казалинского районного маслихата Кызылординской области от 27 июля 2017 года № 120
title:
  rus: Об установлении границы (черты) поселка Айтеке би Казалинского района Кызылординской области
  kaz: Қызылорда облысы Қазалы ауданы Әйтеке би кентінің шекарасын (шегін) белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-11-01
approved_by:
- '161004000001'
- '161004000002'
version_date:
  kaz: 2013-11-01
  rus: 2013-11-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/75687/kaz/01.11.2013
  rus: https://zan.gov.kz/client/#!/doc/75687/rus/01.11.2013
