act_code: '55650'
requisite: Решение от 27.10.2010 №35/4, Акимат г. Кызылорды, Маслихат г. Кызылорды
title:
  rus: Тасбөгет, Белкөл кенттері мен Маханбетов, Досан ауылдарының шекарасын (шегін) өзгерту туралы
  kaz: Тасбөгет, Белкөл кенттері мен Маханбетов, Досан ауылдарының шекарасын (шегін) өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-27
approved_by:
- '161002000001'
- '161002000002'
version_date:
  kaz: 2010-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/55650/kaz/27.10.2010
