act_code: '51290'
requisite: Атырау қалалық әкімиятының 2009 жылғы 1 желтоқсандағы № 1257 қаулысы және Атырау қалалық мәслихатының 2010 жылғы 3 ақпандағы № 179 бірлескен шешімі. Атырау қалалық Әділет басқармасында 2010 жылғы 17 наурызда № 4-1-112 тіркелді
title:
  rus: Атырау қаласындағы жаңадан құрылған көшелерге атау беру және Томарлы селосындағы кейбір көшелердің атын өзгерту туралы
  kaz: Атырау қаласындағы жаңадан құрылған көшелерге атау беру және Томарлы селосындағы кейбір көшелердің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-01
approved_by:
- '156002000001'
- '156002000002'
version_date:
  kaz: 2009-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/51290/kaz/01.12.2009
