act_code: '5851'
requisite: Решение третьей сессии Актюбинского областного маслихата и акима Актюбинской области от 23 февраля 2000 года № 6. Зарегистрировано Управлением юстиции Актюбинской области 25 апреля 2000 года № 482
title:
  rus: О переименовании населенного пункта Эмба-5 на Жем
  kaz: Ембi-5 елдi мекенiн Жем деп өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-02-23
approved_by:
- '153000000001'
- '153000000002'
version_date:
  kaz: 2000-02-23
  rus: 2000-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/5851/kaz/23.02.2000
  rus: https://zan.gov.kz/client/#!/doc/5851/rus/23.02.2000
