act_code: '38330'
requisite: Алматы облысы Ұйғыр аудандық мәслихатының 2008 жылғы 6 ақпандағы № 6-3 шешімі және Ұйғыр ауданының әкімдігінің 2008 жылғы 6 ақпандағы № 2-5 шешімі. Алматы облысының Әділет департаменті Ұйғыр ауданының Әділет басқармасында 2008 жылдың 13 наурызында № 2-19-54 тіркелді. Күші жойылды - Алматы облысы Ұйғыр аудандық мәслихатының 2011 жылғы 21 желтоқсандағы № 55-7 шешімімен
title:
  rus: Ауыл шаруашылығы мақсатындағы жер учаскелерінің жеке меншікте болуы мүмкін ең аз мөлшерін бекіту туралы
  kaz: Ауыл шаруашылығы мақсатындағы жер учаскелерінің жеке меншікте болуы мүмкін ең аз мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-06
approved_by:
- '154008000001'
- '154008000002'
version_date:
  kaz: 2008-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/38330/kaz/06.02.2008
