act_code: '12138'
requisite: Совместное решение маслихата Костанайской области и акима Костанайской области от 15 марта 2002 года № 201/3-с. Зарегистрировано Управлением юстиции Костанайской области 26 апреля 2002 года № 1420. Утратило силу решением маслихата Костанайской области от 15 сентября 2006 года № 347/5
title:
  rus: О предельных (максимальных) размерах земельных участков, которые могут находиться в частной собственности граждан и в долгосрочном землепользовании для ведения товарного сельскохозяйственного производства
  kaz: Азаматтардың жеке меншігіндегі және тауарлы ауыл шаруашылық өндірісін жүргізу үшін ұзақ мерзімді жер пайдалануда болуы мүмкін жер учаскелерінің шекті (ең үлкен) мөлшерін туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-03-15
approved_by:
- '162000000002'
- '162000000003'
version_date:
  kaz: 2002-03-15
  rus: 2002-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/12138/kaz/15.03.2002
  rus: https://zan.gov.kz/client/#!/doc/12138/rus/15.03.2002
