act_code: '18626'
requisite: Атырау облыстық мәслихатының 2004 жылғы 23 қаңтардағы № 68-III және Атырау облысы әкімінің 2004 жылғы 16 қаңтардағы № 6 бірлескен шешiмi. Атырау облысының Әділет департаментінде 2004 жылғы 12 ақпанда № 1837 болып тіркелді
title:
  rus: Әкімшілік-аумақтық бірліктерді тарату туралы
  kaz: Әкімшілік-аумақтық бірліктерді тарату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-01-23
approved_by:
- '156000000001'
- '156000000002'
version_date:
  kaz: 2004-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/18626/kaz/23.01.2004
