act_code: '7947'
requisite: Совместное решение VIII-й сессии Алматинского городского Маслихата II-го созыва и Акима города Алматы от 28 декабря 2000 года N 1196. Зарегистрировано в Управлении юстиции города Алматы 29 декабря 2000 года за N 254. Утратило силу решением Маслихата города Алматы от 14 сентября 2012 № 56
title:
  rus: Об изменении границ города Алматы
  kaz: Алматы қаласы шекарасын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-12-28
approved_by:
- '155000000001'
- '155000000002'
version_date:
  kaz: 2000-12-28
  rus: 2000-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/7947/kaz/28.12.2000
  rus: https://zan.gov.kz/client/#!/doc/7947/rus/28.12.2000
