act_code: '36666'
requisite: Қызылорда облыстық мәслихатының 2007 жылғы 12 желтоқсандағы N 40 және Қызылорда облысы әкімдігінің 2007 жылғы 11 желтоқсандағы N 322 бірлескен қаулысы мен шешімі. Қызылорда облысы Әділет департаментінде 2007 жылғы 26 желтоқсанда N 4196 тіркелді
title:
  rus: Облыс аумағындағы жекелеген елді мекендерді тарату туралы
  kaz: Облыс аумағындағы жекелеген елді мекендерді тарату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '161000000001'
- '161000000002'
version_date:
  kaz: 2007-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/36666/kaz/12.12.2007
