act_code: '12021'
requisite: Совместное решение областного маслихата и Акима Западно-Казахстанской области от 5 апреля 2002 года № 20-2. Зарегистрировано Управлением юстиции Западно-Казахстанской области 23 апреля 2002 года № 1478. Утратило силу решением Западно-Казахстанского областного маслихата от 2 июля 2004 года № 9-4
title:
  rus: Об очередном призыве граждан призывного возраста на срочную военную службу весной и осенью 2002 года
  kaz: 2002 жылдың көктемінде және күзінде шақыру жасындағы азаматтарды мерзімді әскери қызметке кезекті шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-04
approved_by:
- '159000000001'
- '159000000002'
version_date:
  kaz: 2002-04-04
  rus: 2002-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/12021/kaz/04.04.2002
  rus: https://zan.gov.kz/client/#!/doc/12021/rus/04.04.2002
