act_code: '52457'
requisite: Постановление Глубоковского районного акимата от 9 апреля 2010 года № 576, решение Глубоковского районного маслихата Восточно-Казахстанской области от 13 апреля 2010 года № 23/6-IV. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 17 мая 2010 года за № 5-9-131
title:
  rus: Об установлении и изменении границ некоторых населенных пунктов Кировского сельского округа
  kaz: Киров ауылдық округінің кейбір елді мекендерінің шекараларын белгілеп және өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-13
approved_by:
- '157010000001'
- '157010000002'
version_date:
  kaz: 2010-04-13
  rus: 2010-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/52457/kaz/13.04.2010
  rus: https://zan.gov.kz/client/#!/doc/52457/rus/13.04.2010
