act_code: '5832'
requisite: Решение третьей сессии Актюбинского областного маслихата и акима Актюбинской области от 23 февраля 2000 года № 7. Зарегистрировано Управлением юстиции Актюбинской области 25 апреля 2000 года № 478
title:
  rus: О переименовании некоторых сел и школ в Мугалжарском районе
  kaz: Мұғалжар аудандық кейбiр ауылдар мен мектептердiң атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-02-23
approved_by:
- '153000000001'
- '153000000002'
version_date:
  kaz: 2000-02-23
  rus: 2000-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/5832/kaz/23.02.2000
  rus: https://zan.gov.kz/client/#!/doc/5832/rus/23.02.2000
