act_code: '76670'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 25 декабря 2013 года N 188. Зарегистрировано Департаментом юстиции Кызылординской области 13 января 2014 года N 4576. Прекращено действие по истечении срока действия (письмо Сырдарьинского районного маслихата Кызылординской области от 06 января 2015 года N 03-11/02)
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-25
approved_by:
- '161007000002'
- '161007000002'
version_date:
  kaz: 2014-12-03
  rus: 2014-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/76670/kaz/03.12.2014
  rus: https://zan.gov.kz/client/#!/doc/76670/rus/03.12.2014
caused_by:
  code: '84944'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 03 декабря 2014 года N 260. Зарегистрировано Департаментом юстиции Кызылординской области 09 декабря 2014 года N 4813. Прекращено действие по истечении срока действия (письмо Сырдарьинского районного маслихата Кызылординской области от 06 января 2015 года N 03-11/02)
  title:
    rus: О внесении изменений в решение районного маслихата от 25 декабря 2013 года N 188 "О районном бюджете на 2014-2016 годы"
    kaz: '"2014-2016 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2013 жылғы 25 желтоқсандағы N 188 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/84944/rus
