act_code: '34733'
requisite: Решение XXXI-й сессии маслихата города Алматы III-го созыва от 20 июля 2007 года N 382 и постановление Акимата города Алматы от 31 июля 2007 года N 5/822. Зарегистрировано Департаментом юстиции города Алматы 9 августа 2007 года за N 753
title:
  rus: О предельных (максимальных) размерах земельных участков, которые могут находиться в частной собственности граждан Республики Казахстан
  kaz: Қазақстан Республикасы азаматтарының жеке меншігінде болуы мүмкін жер учаскелерінің шекті (ең жоғары) мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-20
approved_by:
- '155000000001'
- '155000000002'
version_date:
  kaz: 2007-07-20
  rus: 2007-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/34733/kaz/20.07.2007
  rus: https://zan.gov.kz/client/#!/doc/34733/rus/20.07.2007
