act_code: '55993'
requisite: Совместное постановление акимата Кызылжарского района Северо-Казахстанской области от 10 ноября 2010 года № 443 и решение маслихата Кызылжарского района Северо-Казахстанской области от 17 ноября 2010 года № 29/18. Зарегистрировано Управлением юстиции Кызылжарского района Северо-Казахстанской области 21 декабря 2010 года № 13-8-135
title:
  rus: Об изменении границ села Байтерек Кызылжарского сельского округа и села Подгорное Кызылжарского сельского округа Кызылжарского района
  kaz: Қызылжар ауданы Қызылжар ауылдық округі Бәйтерек ауылы және Қызылжар ауылдық округі Подгорное ауылының шекараларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-17
approved_by:
- '165008000001'
- '165008000002'
version_date:
  kaz: 2018-11-26
  rus: 2018-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/55993/kaz/26.11.2018
  rus: https://zan.gov.kz/client/#!/doc/55993/rus/26.11.2018
caused_by:
  code: '126327'
  requisite: Совместное постановление акимата Кызылжарского района Северо-Казахстанской области от 26 ноября 2018 года № 450 и решение Кызылжарского районного маслихата Северо-Казахстанской области от 26 ноября 2018 года № 34/3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 ноября 2018 года № 5020
  title:
    rus: О внесении изменений в совместное постановление акимата Кызылжарского района Северо-Казахстанской области от 10 ноября 2010 года № 443 и решение Кызылжарского районного маслихата Северо-Казахстанской области от 17 ноября 2010 года № 29/18 «Об изменении границ аула Байтерек Кызылжарского сельского округа и села Подгорное Кызылжарского сельского округа Кызылжарского района»
    kaz: Солтүстік Қазақстан облысы Қызылжар аудандық әкімдігінің 2010 жылғы 10 қарашадағы № 443 және Солтүстік Қазақстан облысы Қызылжар аудандық мәслихатының 2010 жылғы 17 қарашадағы № 29/18 «Қызылжар ауданы Қызылжар селолық округі Бәйтерек ауылы және Қызылжар селолық округі Подгорное селосының шекараларын өзгерту туралы» біріккен қаулысы мен шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126327/rus
