act_code: '3072'
requisite: Решение Костанайского областного маслихата и акима Костанайской области (шестнадцатая сессия) от 28 августа 1998 года. Зарегистрировано управлением юстиции Костанайской области 23 марта 1999 года № 67
title:
  rus: О переименовании села Шобанколь Аулиекольского района Костанайской области в село К. Тургымбаева
  kaz: Қостанай облысы Әулиекөл ауданының Шобанкөл ауылын Қ. Тұрғымбаев ауылы деп қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-08-27
approved_by:
- '162000000001'
- '162000000002'
version_date:
  kaz: 1998-08-27
  rus: 1998-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/3072/kaz/27.08.1998
  rus: https://zan.gov.kz/client/#!/doc/3072/rus/27.08.1998
