act_code: '12277'
requisite: Совместное решение Северо-Казахстанского областного маслихата и акима Северо-Казахстанской области от 19 апреля 2002 года № 17/6-3. Зарегистрировано Управлением юстиции Северо-Казахстанской области 24 мая 2002 года за № 648. Утратило силу - совместным постановлением акимата Северо-Казахстанской области от 23 июля 2010 года № 196 и решением маслихата Северо-Казахстанской области от 23 июля 2010 года № 27/11
title:
  rus: Об утверждении предельных (максимальных) размеров земельных участков, которые могут находиться в собственности граждан и в долгосрочном землепользовании для ведения товарного сельскохозяйственного производства
  kaz: Азаматтардың меншігіне берілетін және ауыл шаруашылық өндірісін жүргізу үшін ұзақ мерзімді жер пайдалануда болуы мүмкін жер учаскелерінің шекті (ең үлкен) мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-18
approved_by:
- '165000000002'
- '165000000003'
version_date:
  kaz: 2004-04-14
  rus: 2004-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/12277/kaz/14.04.2004
  rus: https://zan.gov.kz/client/#!/doc/12277/rus/14.04.2004
caused_by:
  code: '19884'
  requisite: Совместное решение Северо-Казахстанского областного маслихата и акима области (VI сессия третьего созыва) от 15 апреля 2004 года № 6/16-2. Зарегистрировано Департаментом юстиции Республики Казахстан 19 мая 2004 года № 1259. Утратило силу - решением маслихата Северо-Казахстанской области от 18 июня 2010 года № 26/15
  title:
    rus: О признании утратившим силу п.2 совместного решения областного маслихата и акима области № 17/6-3 "Об утверждении предельных (максимальных) размеров земельных участков, которые могут находиться в собственности граждан и в долгосрочном землепользовании для ведения товарного (сельскохозяйственного) производства."
    kaz: Облыстық мәслихаттың және облыс әкімінің "Тауарлы (ауыл шаруашылығы) өндiрiсiн жүргiзу үшiн азаматтардың меншiгiнде бола алатын және ұзақ мерзiмде пайдалана алатын жер учаскелерiнiң шектеулi (ең үлкен) мөлшерiн бекіту туралы" № 17/6-3 бірлескен шешімінiң 2-тармағы күшiн жойды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/19884/rus
