act_code: '17076'
requisite: Совместное решение Западно-Казахстанского областного маслихата и акимата Западно-Казахстанской области от 23 августа 2003 года № 34-5 и № 165. Зарегистрировано Управлением юстиции Западно-Казахстанской области 22 сентября 2003 № 2294
title:
  rus: О предельных (максимальных) размерах земельных участков, которые могут находиться в частной собственности граждан Республики Казахстан по Западно-Казахстанской области
  kaz: Батыс Қазақстан облысы бойынша Қазақстан Республикасы азаматтарының жеке меншігінде болуы мүмкін жер учаскелерінің шекті (ең жоғары) мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-08-22
approved_by:
- '159000000001'
- '159000000002'
version_date:
  kaz: 2003-08-22
  rus: 2003-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/17076/kaz/22.08.2003
  rus: https://zan.gov.kz/client/#!/doc/17076/rus/22.08.2003
