act_code: '12420'
requisite: Решение акима Жамбылской области и Жамбылского областного маслихата от 25 мая 2002 года № 13-10. Зарегистрировано Управлением юстиции Жамбылской области 12 июня 2002 года за № 631
title:
  rus: О создании аульных (сельских) и поселкового округов
  kaz: Ауылдық (селолық) және кенттік округтерді құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-05-24
approved_by:
- '158000000001'
- '158000000002'
version_date:
  kaz: 2002-05-24
  rus: 2002-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/12420/kaz/24.05.2002
  rus: https://zan.gov.kz/client/#!/doc/12420/rus/24.05.2002
