act_code: '56086'
requisite: Постановление акимата города Актау Мангистауской области от 30 ноября 2010 года № 1147 и решение Актауского городского маслихата Мангистауской области от 30 ноября 2010 года №37/334. Утратило силу постановлением акимата города Актау Мангистауской области от 11 марта 2016 года № 409 и решением Актауского городского маслихата Мангистауской области от 11 марта 2016 года № 38/384.
title:
  rus: О наименовании "Проспектом Независимости" дороги от здания областного акимата, расположенного в 14 микрорайоне города Актау, до трассы "Актау-Бейнеу"
  kaz: Ақтау қаласы 14 шағын ауданында орналасқан облыстық әкімдік ғимаратынан бастап "Ақтау - Бейнеу" тас жолына дейінгі аралықтағы жолды "Тәуелсіздік даңғылы" деп атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-30
approved_by:
- '163002000001'
- '163002000002'
version_date:
  kaz: 2014-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/56086/kaz/11.09.2014
caused_by:
  code: '94236'
  requisite: 'Решение от 11.09.2014 №24/222 Маслихат города Актау и постановление от 11.09.2014 № 1292 акимат города Актау '
  title:
    rus: 'Об отмене совместного постановления и решения акимата города №1147 и городского маслихата №37/334 от 30 ноября 2010 года «О наименовании «Проспектом независимости» дороги от здания областного акимата, расположенного в 14 микрорайоне города Актау, до трассы «Актау-Бейнеу» '
    kaz: '«Ақтау қаласы 14 шағын ауданындағы облыстық әкімдік ғимаратынан бастап «Ақтау-Бейнеу» тас жолына дейінгі аралықтағы жолды «Тәуелсіздік даңғылы» деп атау туралы» 2010 жылғы 30 қарашадағы қала әкімдігінің №1147 және қалалық мәслихаттың №37/334 бірлескен қаулысы мен шешімін жою туралы '
  link: https://zan.gov.kz/client/#!/doc/94236/rus
