act_code: '51952'
requisite: Атырау қалалық мәслихатының 2010 жылғы 9 сәуірдегі № 191 бірлескен шешімі және қалалық әкімиятының 2010 жылғы 1 сәуірдегі № 280 қаулысы. Атырау қалалық Әділет басқармасында 2010 жылғы 23 сәуірде № 4-1-115 тіркелді
title:
  rus: Атырау қаласы мен ауылдық округ көшелеріне атау беру және кейбір көшелердің атын өзгерту туралы
  kaz: Атырау қаласы мен ауылдық округ көшелеріне атау беру және кейбір көшелердің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-09
approved_by:
- '156002000001'
- '156002000002'
version_date:
  kaz: 2014-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/51952/kaz/04.12.2014
