act_code: '67314'
requisite: Решение маслихата Павлодарской области от 03 августа 2012 года № 77/7 и постановление акимата Павлодарской области от 07 августа 2012 года № 10. Зарегистрировано Департаментом юстиции Павлодарской области 27 августа 2012 года № 3215
title:
  rus: Об изменении в административно-территориальном устройстве города Павлодара
  kaz: Павлодар қаласының әкімшілік-аумақтық құрылымындағы өзгерістер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-08-03
approved_by:
- '164000000001'
- '164000000002'
version_date:
  kaz: 2012-08-03
  rus: 2012-08-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/67314/kaz/03.08.2012
  rus: https://zan.gov.kz/client/#!/doc/67314/rus/03.08.2012
