act_code: '51943'
requisite: Маңғыстау ауданы әкімдігі Тұщықұдық селосы әкімі аппаратының 2010 жылғы 7 сәуірдегі № 14 шешімі. Маңғыстау ауданының Әділет басқармасында 2010 жылғы 15 сәуірде № 11-5-100 тіркелді. Күші жойылды – Маңғыстау облысы Маңғыстау ауданы әкімдігі Тұщықұдық селолық округі әкімі аппаратының 2016 жылғы 16 мамырдағы № 31 шешімімен
title:
  rus: Тұщықұдық селолық округінің құрамдас бөліктеріне атау беру туралы
  kaz: Тұщықұдық селолық округінің құрамдас бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-07
approved_by:
- '163004000001'
- '163004004001'
version_date:
  kaz: 2010-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/51943/kaz/07.04.2010
