act_code: '39372'
requisite: Совместное решение маслихата города Семей от 22 апреля 2008 года № 7/64-IV и постановление акимата города Семей Восточно-Казахстанской области от 22 апреля 2008 года № 447. Зарегистрировано в Управлении юстиции города Семей Департамента юстиции Восточно-Казахстанской области 6 мая 2008 года за № 5-2-88
title:
  rus: О переименовании улицы
  kaz: Көше атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-22
approved_by:
- '157003000001'
- '157003000002'
version_date:
  kaz: 2008-04-22
  rus: 2008-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/39372/kaz/22.04.2008
  rus: https://zan.gov.kz/client/#!/doc/39372/rus/22.04.2008
