act_code: '10770'
requisite: Совместное решение Акима Акмолинской области и Акмолинского областного маслихата от 31 октября 2001 года № С-11-6. Зарегистрировано Управлением юстиции Акмолинской области 19 декабря 2001 года № 871
title:
  rus: Об изменении границы г.Кокшетау и образовании Красноярского сельского округа
  kaz: Көкшетау қаласының шекарасын өзгерту және Краснояр селолық округін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-10-31
approved_by:
- '152000000001'
- '152000000002'
version_date:
  kaz: 2001-10-31
  rus: 2001-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/10770/kaz/31.10.2001
  rus: https://zan.gov.kz/client/#!/doc/10770/rus/31.10.2001
