act_code: '912'
requisite: Решение Алматинского областного маслихата от 14 мая 1998 года № 5-170 и решение акима Алматинской области от 17 апреля 1998 года № 20-157. Зарегистрировано управлением юстиции Алматинской области 16 июля 1998 года № 21
title:
  rus: Решение об изменении границ города областного значения "Капчагай" Алматинской области
  kaz: Алматы облысындағы облыстық мәнi бар Қапшағай қаласының шекарасын өзгерту
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-05-13
approved_by:
- '154000000002'
- '154000000003'
version_date:
  kaz: 2010-04-13
  rus: 2010-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/912/kaz/13.04.2010
  rus: https://zan.gov.kz/client/#!/doc/912/rus/13.04.2010
caused_by:
  code: '52698'
  requisite: Решение маслихата Алматинской области от 12 апреля 2010 года № 32-194 и постановление акимата Алматинской области от 13 апреля 2010 года № 45а. Зарегистрировано Департаментом юстиции Алматинской области 11 мая 2010 года № 2050
  title:
    rus: О внесении изменений в совместное решение акима Алматинской области N 5-170 от 14 мая 1998 года и Алматинского областного маслихата N 20-157 от 17 апреля 1998 года "Об изменении границ города областного значения "Капчагай" Алматинской области и придании статуса особо охраняемой природной
    kaz: Алматы облысы әкімінің 1998 жылғы 14 мамырдағы N 5-170 және Алматы облысы мәслихатының 1998 жылғы 17 сәуірдегі N 20-157 "Алматы облысындағы облыстық мәні бар Қапшағай қаласының шекарасын өзгерту және оған ерекше қорғалатын табиғи аумақ мәртебесін беру тралы" бірлескен шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/52698/rus
