act_code: '10518'
requisite: Совместное решение Северо-Казахстанского областного маслихата и акима Северо-Казахстанской области от 12 октября 2001 года № 13/5-70. Зарегистрировано Управлением юстиции Северо-Казахстанской области 19 ноября 2001 года за № 485
title:
  rus: Об изменениях в административно-территориальном устройстве Тимирязевского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тимирязев ауданының әкімшілік-аумақтық құрылымындағы өзгерістер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-10-11
approved_by:
- '165000000002'
- '165000000003'
version_date:
  kaz: 2001-10-11
  rus: 2001-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/10518/kaz/11.10.2001
  rus: https://zan.gov.kz/client/#!/doc/10518/rus/11.10.2001
