act_code: '73189'
requisite: Совместное решение маслихата Актюбинской области от 27 июня 2013 года № 132 и постановление акимата Актюбинской области от 27 июня 2013 года № 197. Зарегистрировано Департаментом юстиции Актюбинской области 1 июля 2013 года № 3599
title:
  rus: Об изменениях в административно-территориальном устройстве Темирского района
  kaz: Темір ауданының әкімшілік-аумақтық құрылысындағы өзгерістер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-06-27
approved_by:
- '153000000001'
- '153000000002'
version_date:
  kaz: 2013-06-27
  rus: 2013-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/73189/kaz/27.06.2013
  rus: https://zan.gov.kz/client/#!/doc/73189/rus/27.06.2013
