act_code: '2755'
requisite: Решение Костанайского областного маслихата и Акима Костанайской области (внеочередная сессия) от 7 апреля 1999 года. Зарегистрировано Управлением юстиции Костанайской области 28 апреля 1999 года № 80
title:
  rus: Об изменениях в административно-территориальном устройстве Джангельдинского и Наурзумского районов
  kaz: Жангелдин және Науырзым аудандарының әкімшілік-аумақтық құрылымындағы өзгертулер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-06
approved_by:
- '162000000001'
- '162000000002'
version_date:
  kaz: 2014-07-04
  rus: 2014-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/2755/kaz/04.07.2014
  rus: https://zan.gov.kz/client/#!/doc/2755/rus/04.07.2014
caused_by:
  code: '81388'
  requisite: Постановление акимата Костанайской области от 4 июля 2014 года № 9 и решение маслихата Костанайской области от 4 июля 2014 года № 297. Зарегистрировано Департаментом юстиции Костанайской области 14 июля 2014 года № 4936
  title:
    rus: О внесении изменений в некоторые совместные решения акима и решения маслихата, постановления акимата и решения маслихата об изменениях в административно-территориальном устройстве Костанайской области
    kaz: Қостанай облысының әкімшілік-аумақтық құрылысындағы өзгерістер туралы кейбір бірлескен әкімнің шешімдері мен мәслихаттың шешімдеріне, әкімдіктің қаулылары мен мәслихаттың шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/81388/rus
