act_code: '3044'
requisite: Решение двадцать четвертой сессии Актюбинского областного Маслихата и Акима Актюбинской области oт 21 апреля 1999 года N 8. Зарегистрировано Управлением юстиции Актюбинской области 21 мая 1999 года № 110
title:
  rus: Об изменениях в административно-территориальном устройстве Хромтауского района
  kaz: Хромтау ауданының әкiмшiлiк-аумақтық құрылысындағы өзгерiстер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-20
approved_by:
- '153000000001'
- '153000000002'
version_date:
  kaz: 1999-04-20
  rus: 1999-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/3044/kaz/20.04.1999
  rus: https://zan.gov.kz/client/#!/doc/3044/rus/20.04.1999
