act_code: '19764'
requisite: Совместное решение маслихата Актюбинской области и акимата Актюбинской области от 22 апреля 2004 года № 52/3. Зарегистрировано Департаментом юстиции Актюбинской области 14 мая 2004 года № 2718
title:
  rus: Об очередном призыве граждан на срочную военную службу в апреле-июне и октябре-декабре 2004 года
  kaz: 2004 жылдың сәуір-маусым және қазан-желтоқсанында азматтарды мерзімді әскери қызметке шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-04-21
approved_by:
- '153000000001'
- '153000000002'
version_date:
  kaz: 2004-04-21
  rus: 2004-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/19764/kaz/21.04.2004
  rus: https://zan.gov.kz/client/#!/doc/19764/rus/21.04.2004
