act_code: '16235'
requisite: Атырау облыстық мәслихатының XXIV сессиясында қабылданған ІІ сайланған 2003 жылғы 6 маусымдағы № 312-ІІ шешімі. Атырау облыстық Әділет басқармасында 2003 жылы 14 шілдеде № 1562 болып тіркелді
title:
  rus: Атырау облысы Құрманғазы ауданының Ақкөл поселкесін ауыл санатына жатқызу туралы
  kaz: Атырау облысы Құрманғазы ауданының Ақкөл поселкесін ауыл санатына жатқызу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-06-05
approved_by:
- '156000000001'
- '156000000002'
version_date:
  kaz: 2003-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/16235/kaz/05.06.2003
