act_code: '46271'
requisite: Решение от 28.04.2009 №135, Акимат Казалинского района, Маслихат Казалинского района
title:
  rus: Әйтеке би кентінің шекарасын (шегін) белгілеу және өзгерту туралы
  kaz: Әйтеке би кентінің шекарасын (шегін) белгілеу және өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-28
approved_by:
- '161004000001'
- '161004000002'
version_date:
  kaz: 2009-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/46271/kaz/28.04.2009
