act_code: '668'
requisite: Решение Председателя Комитета по стандартизации, метрологии и сертификации Министерства энергетики, индустрии и торговли Республики Казахстан от 3 апреля 1998 года, Вице-Министра сельского хозяйства Республики Казахстан от 31 марта 1998 года. Зарегистрированo в Министерстве юстиции Республики Казахстан 20 мая 1998 года № 513. Утратило силу совместным приказом Заместителя Премьер-Министра Республики Казахстан - Министр индустрии и новых технологий Республики Казахстан и Министра сельского хозяйства Республики Казахстан от 23 ноября 2012 года № 418
title:
  rus: По вопросу выдачи ассортиментных номеров продукции и порядковых учетных номеров предприятиям-производителям консервной продукции
  kaz: Шешім консерві өнімін өндіруші кәсіпорындардың өніміне ассортименттік нөмір және реттік есеп нөмірін беру мәселесі жөнінде
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-04-02
approved_by:
- '103012000000'
- '103017001000'
version_date:
  kaz: 1998-04-02
  rus: 1998-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/668/kaz/02.04.1998
  rus: https://zan.gov.kz/client/#!/doc/668/rus/02.04.1998
