act_code: '28967'
requisite: Совместное решение маслихата Костанайского района Костанайской области и акимата Костанайского района Костанайской области от 12 июля 2006 года № 321/3с. Зарегистрировано Управлением юстиции Костанайского района Костанайской области 19 июля 2006 года № 9-14-41. Утратило силу совместными постановлением акимата Костанайского района Костанайской области от 17 июля 2020 года № 392 и решением маслихата Костанайского района Костанайской области от 17 июля 2020 года № 544 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об изменении границ (черты) поселка Затобольск
  kaz: Затобол кентінің шекарасын (шегін) өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-07-12
approved_by:
- '162012000001'
- '162012000002'
version_date:
  kaz: 2006-06-12
  rus: 2006-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/28967/kaz/12.06.2006
  rus: https://zan.gov.kz/client/#!/doc/28967/rus/12.06.2006
