act_code: '24467'
requisite: Совместное решение маслихата Северо-Казахстанской области от 27 мая 2005 года № 16/5 и решение акима Северо-Казахстанской области от 26 мая 2005 года № 2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 16 июня 2005 года № 1588. Утратило силу - решением акима Северо-Казахстанской области от 26 сентября 2011 года № 27
title:
  rus: Об организации призыва граждан Республики Казахстан на срочную военную службу на территории области в апреле-июне и октябре-декабре 2005 года
  kaz: 2005 жылдың сәуiр-маусымында және қазан-желтоқсанында облыс аумағындағы Қазақстан Республикасы азаматтарының мерзiмдi әскери қызметке шақырылуын ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-05-27
approved_by:
- '165000000001'
- '165000000002'
version_date:
  kaz: 2005-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/24467/kaz/27.05.2005
