act_code: '85013'
requisite: Решение Кызылординского областного маслихата от 21 ноября 2014 года N 233. Зарегистрировано Департаментом юстиции Кызылординской области 12 декабря 2014 года N 4817. Утратило силу решением Кызылординского областного маслихата от от 17 марта 2021 года № 14
title:
  rus: Об утверждении границы охранной зоны, зоны регулирования застройки и зоны охраняемого природного ландшафта памятника истории и культуры "Городище Жанкент", расположенного в Казалинском районе
  kaz: Қазалы ауданында орналасқан "Жанкент қалашығы" тарих және мәдениет ескерткішінің қорғау аймағының, құрылыс салуды реттеу аймағының және қорғалатын табиғат ландшафт аймағының шекарасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-20
approved_by:
- '161000000002'
- '161000000002'
version_date:
  kaz: 2014-11-21
  rus: 2014-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/85013/kaz/21.11.2014
  rus: https://zan.gov.kz/client/#!/doc/85013/rus/21.11.2014
