act_code: '11051'
requisite: Решение от 25.12.2001 №16/152, Аким Мангистауской области
title:
  rus: Об образовании Шебирского сельского округа Мангистауского района
  kaz: Маңғыстау ауданының Шебiр ауылдық округiн құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-25
approved_by:
- '163000000001'
- '163000000002'
version_date:
  rus: 2015-05-21
source:
  rus: https://zan.gov.kz/client/#!/doc/11051/rus/21.05.2015
