act_code: '11051'
requisite: Решение от 25.12.2001 №16/152, Аким Мангистауской области
title:
  rus: Об образовании Шебирского сельского округа Мангистауского района
  kaz: Маңғыстау ауданының Шебiр ауылдық округiн құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-25
approved_by:
- '163000000001'
- '163000000002'
version_date:
  kaz: 2015-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/11051/kaz/21.05.2015
caused_by:
  code: '91292'
  requisite: Решение от 21.05.2015 №25/390, Маслихат Мангистауской области и постановление   от 21.05.2015 № 148, Акимат Мангистауской области
  title:
    rus: 'О внесении изменений в совместное решение Мангистауского областного маслихата и акима Мангистауской области,в некоторые постановления акимата Мангистауской области и решения Мангистауского областного маслихата '
    kaz: 'Маңғыстау облыстық мәслихаты мен Маңғыстау облысы әкімінің  бірлескен шешіміне,кейбір Маңғыстау облысы әкімдігінің қаулылары мен Маңғыстау облыстық мәслихатының шешімдеріне өзгерістер енгізу туралы '
  link: https://zan.gov.kz/client/#!/doc/91292/rus
