act_code: '8867'
requisite: Совместное решение Западно-Казахстанского областного маслихата и акима Западно-Казахстанской области от 25 марта 2001 года № 10-10. Зарегистрировано управлением юстиции Западно-Казахстанской области 15 мая 2001 года за № 853. Утратило силу постановлением акимата Западно-Казахстанской области от 12 марта 2025 года № 56 и решением Западно-Казахстанского областного маслихата от 12 марта 2025 года № 17-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании Деркульского, Желаевского, Зачаганского и Круглоозерновского поселковых округов города Уральска
  kaz: Орал қаласының Деркөл, Желаев, Зачаган және Круглоозерный поселкелік округтерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-03-25
approved_by:
- '159000000001'
- '159000000002'
version_date:
  kaz: 2001-03-25
  rus: 2001-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/8867/kaz/25.03.2001
  rus: https://zan.gov.kz/client/#!/doc/8867/rus/25.03.2001
