act_code: '12103'
requisite: Совместное решение Акима Акмолинской области и Акмолинского областного маслихата от 12 апреля 2002 года № С-16-12/35. Зарегистрированно управлением юстиции Акмолинской области 6 мая 2002 года № 1081
title:
  rus: Об изменении границ некоторых сельских округов и поселка Боровое
  kaz: Кейбір селолық округтер мен Бурабай поселкесінің шекараларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-11
approved_by:
- '152000000001'
- '152000000002'
version_date:
  kaz: 2002-04-11
  rus: 2002-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/12103/kaz/11.04.2002
  rus: https://zan.gov.kz/client/#!/doc/12103/rus/11.04.2002
