act_code: '6736'
requisite: Решение Акмолинского областного маслихата и акима Акмолинской области от 15 июня 2000 года № С-3-03. Зарегистрировано Управлением юстиции Акмолинской области 24 июля 2000 года № 262
title:
  rus: Об изменении границ некоторых сельских округов
  kaz: Жекелеген селолық округтердің шекарасын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-06-14
approved_by:
- '152000000001'
- '152000000002'
version_date:
  kaz: 2000-06-14
  rus: 2000-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/6736/kaz/14.06.2000
  rus: https://zan.gov.kz/client/#!/doc/6736/rus/14.06.2000
