act_code: '51291'
requisite: Атырау қалалық әкімиятының 2009 жылғы 1 желтоқсандағы № 1258 қаулысы және Атырау қалалық мәслихатының 2010 жылғы 3 ақпандағы № 180 бірлескен шешімі. Атырау қалалық Әділет басқармасында 2010 жылғы 17 наурызда № 4-1-113 тіркелді
title:
  rus: Атырау қаласына қарасты өткелге, көшелер мен көпірлерге атау беру және өзгерту туралы
  kaz: Атырау қаласына қарасты өткелге, көшелер мен көпірлерге атау беру және өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-01
approved_by:
- '156002000001'
- '156002000002'
version_date:
  kaz: 2009-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/51291/kaz/01.12.2009
