act_code: '53834'
requisite: Бірлескен Ақтөбе облысы Хромтау аудандық мәслихатының 2010 жылғы 26 шілдедегі № 196 шешімі және Ақтөбе облысы Хромтау аудандық әкімдігінің 2010 жылғы 26 шілдедегі № 150 қаулысы. Ақтөбе облысы Хромтау ауданының Әділет басқармасында 2010 жылғы 6 тамызда № 3-12-122 тіркелді
title:
  rus: Хромтау қаласының көшесін қайта атау туралы
  kaz: Хромтау қаласының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-26
approved_by:
- '153013000001'
- '153013000002'
version_date:
  kaz: 2010-07-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/53834/kaz/26.07.2010
