act_code: '53834'
requisite: Бірлескен Ақтөбе облысы Хромтау аудандық мәслихатының 2010 жылғы 26 шілдедегі № 196 шешімі және Ақтөбе облысы Хромтау аудандық әкімдігінің 2010 жылғы 26 шілдедегі № 150 қаулысы. Ақтөбе облысы Хромтау ауданының Әділет басқармасында 2010 жылғы 6 тамызда № 3-12-122 тіркелді
title:
  rus: Хромтау қаласының көшесін қайта атау туралы
  kaz: Хромтау қаласының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-26
approved_by:
- '153013000001'
- '153013000002'
version_date:
  kaz: 2018-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/53834/kaz/28.11.2018
caused_by:
  code: '127656'
  requisite: Постановление акимата Хромтауского района Актюбинской области от 28 ноября 2018 года № 267 и решение маслихата Хромтауского района Актюбинской области от 28 ноября 2018 года № 255. Зарегистрировано Управлением юстиции Хромтауского района Департамента юстиции Актюбинской области 20 декабря 2018 года № 3-12-193
  title:
    rus: О внесении изменения в совместное постановление и решение Хромтауского районного акимата и маслихата от 26 июля 2010 года № 150/196 «О переименовании улицы города Хромтау»
    kaz: Хромтау аудандық әкімдігінің және мәслихаттың 2010 жылғы 26 шілдедегі № 150/196 «Хромтау қаласының көшесін қайта атау туралы» бірлескен қаулысы мен шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127656/rus
