act_code: '41914'
requisite: Алматы облысы Кербұлақ ауданы әкімінің 2008 жылғы 17 қыркүйектегі № 30 шешімі және Кербұлақ аудандық мәслихатының 2008 жылғы 17 қыркүйектегі № 11-87 шешімі. Алматы облысының Әділет департаменті Кербұлақ ауданының әділет басқармасында 2008 жылы 15 қазанда № 2-13-78 тіркелді. Күші жойылды - Алматы облысы Кербұлақ аудандық мәслихатының 2009 жылғы 28 тамыздағы № 23-163 шешімімен
title:
  rus: Қаспан ауылының шекарасын ұлғайту туралы
  kaz: Қаспан ауылының шекарасын ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-09-17
approved_by:
- '154010000001'
- '154010000002'
version_date:
  kaz: 2008-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/41914/kaz/17.09.2008
