act_code: '59767'
requisite: Решение Кызылординского городского маслихата от 14 июня 2011 года N 43/5. Зарегистрировано Департаментом юстиции Кызылординской области 21 июля 2011 года N 10-1-182
title:
  rus: Об утверждении базовых ставок земельного налога с юридических лиц и физических лиц, занимающися предпринимательской деятельностью на территории города Кызылорда
  kaz: Қызылорда қаласының аумағында заңды тұлғалар мен кәсіпкерлік қызметпен айналысатын жеке тұлғалардан алынатын жер салығының базалық мөлшерлемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-14
approved_by:
- '161002000002'
- '161002000002'
version_date:
  kaz: 2011-06-14
  rus: 2011-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/59767/kaz/14.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59767/rus/14.06.2011
