act_code: '73250'
requisite: Решение Кызылординского городского маслихата от 20 июня 2013 года N 18/2. Зарегистрировано Департаментом юстиции Кызылординской области 01 июля 2013 года N 4469
title:
  rus: О единых ставках фиксированного налога по городу Кызылорда
  kaz: Қызылорда қаласы бойынша бірыңғай тіркелген салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-06-20
approved_by:
- '161002000002'
- '161002000002'
version_date:
  kaz: 2013-06-20
  rus: 2013-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/73250/kaz/20.06.2013
  rus: https://zan.gov.kz/client/#!/doc/73250/rus/20.06.2013
