act_code: '55331'
requisite: Алматы облысы Ұйғыр аудадық мәслихатының 2010 жылғы 29 қыркүйектегі № 39-8 шешімі және Ұйғыр ауданы әкімдігінің 2010 жылғы 29 қыркүйектегі № 29-314 қаулысы. Алматы облысының Әділет департаменті Ұйғыр ауданының Әділет басқармасында 2010 жылы 05 қарашада № 2-19-107 тіркелді
title:
  rus: Ұйғыр ауданы елді мекендерінің шекарасын өзгерту және белгілеу туралы
  kaz: Ұйғыр ауданы елді мекендерінің шекарасын өзгерту және белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-29
approved_by:
- '154008000001'
- '154008000002'
version_date:
  kaz: 2010-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/55331/kaz/29.09.2010
